---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cloudbandits/farseer_front:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: sb
            - name: REACT_APP_BACKEND_URL
              value: http://backend:8000
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m